databases:
  - name: django_db
    databaseName: django_db
    user: django_user
    plan: free

services:
  - type: web
    name: django-app
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn core.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DEBUG
        value: "False"
